### PR TITLE
Automated tests

### LINKED ISSUE #1: Make code conform to PEP 8
We'd like the code to comply with http://www.python.org/dev/peps/pep-0008/ and have a script we can run to detect (and hopefully fix) code that is not compliant.

### PR DESCRIPTION
**Pull request by rliebz**
Purpose
---
Add automated testing

Changes
---
 - Tests now use a temporary user, eliminating the need for an API token to be provided
 - Add Travis configuration
 - Add flake8 for style checking
 - Improve PEP8 conformity (mostly line length issues)
 - Refactor URLs to reduce repetition
 - Resolves #1, #19, #22

### CODE REVIEW

**Comment by rliebz** [comment]
@pdurbin, this requires someone with administrative privilege to visit https://travis-ci.org/profile/IQSS and enable this repository for both pushes and pull requests.

**Comment by pdurbin** [comment]
@rliebz I am absolutely **thrilled** by all the work you've done and how you're pulling us into the modern world of Travis.

However, I need to read through the following links before I authorize the app per the screenshot below. Thanks for understanding. I hope to get to this soon!

- https://help.github.com/articles/connecting-with-third-party-applications#hooks
- https://help.github.com/articles/connecting-with-third-party-applications#commit-status
- https://help.github.com/articles/connecting-with-third-party-applications#deployments

authorize_travis_ci_-_2015-05-15_13 17 44

**Comment by rliebz** [comment]
:+1:

**Comment by astrofrog** [comment]
@rliebz - just in case you haven't done this already, you can also enable travis for your fork in the mean time, so you can already test if things are working (maybe you've done this already?)

**Comment by rliebz** [comment]
@astrofrog, thanks for the tip. I will set that up and take a look at fixing the branch when I have the time.

**Comment by astrofrog** [comment]
@pdurbin - following up on our conversation today, did the repository appear on Travis in the end?

**Comment by pdurbin** [comment]
@astrofrog looked over my shoulder but even though I authorized the app I'm seeing this:

philip_durbin_-_profile_-_travis_ci_-_2015-05-21_17 25 26

@rliebz @astrofrog any advice?

**Comment by pdurbin** [comment]
Maybe I should revoke access and try again?

connection_with_travis_ci_-_2015-05-21_17 29 46

**Comment by astrofrog** [comment]
I don't understand, since you are a member of IQSS. But it just hit me, are you maybe not an admin in the IQSS organization? (you should check what permissions you have there, i.e. admin vs write permissions)

**Comment by pdurbin** [comment]
I'm an "owner" of @IQSS, the highest level.

**Comment by astrofrog** [comment]
@pdurbin - try asking support@travis-ci.com - they are usually very responsive.

**Comment by BanzaiMan** [comment]
Hello. I've resync'd data for all users belonging to IQSS. This should now allow an admin to enable Travis CI on this repository. Please try, and let me know how it goes.

Thanks.

**Comment by pdurbin** [comment]
@BanzaiMan thanks! Things seem to be happening now!

**Comment by pdurbin** [comment]
Ok, Travis in general is working fine for @IQSS because I just got this passing: https://travis-ci.org/IQSS/dataverse-android/builds

@rliebz @astrofrog I have no idea why test aren't passing for this Python library though. Help! :)

**Comment by rliebz** [comment]
Since I've gotten tests passing locally but not with travis, it's almost certainly an issue with the travis configuration file. I'll try to take a look when I get the chance, but I won't have access to a computer for the next week.

**Comment by pdurbin** [comment]
@rliebz no rush! Thanks for getting me into Travis! :)

**Comment by astrofrog** [comment]
@rliebz - the issue is because the test dependencies are not being picked up by pip. I think you can fix this by adding a ``pip install httpretty pytest`` to the install section

**Comment by pdurbin** [comment]
@astrofrog thanks! I tried that in a1becfe and I'm seeing some progress! In the server logs at https://apitest.dataverse.org

```
[2015-05-22T08:31:17.887-0400] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=49 _ThreadName=Thread-8] [timeMillis: 1432297877887] [levelValue: 800] [[
  ADDING FILE: cat.jpg; for dataset: doi:10.5072/FK2/EYAGB6]]
```

This is from https://travis-ci.org/IQSS/dataverse-client-python/jobs/63642046

**Comment by astrofrog** [comment]
@pdurbin - for the timeout, this can sometimes happen as a one-off, in that case you can restart the offending build on Travis. It might be worth opening a new PR re-enabling 3.4 to see if the error is still happening.

**Comment by pdurbin** [comment]
@astrofrog the Python 3.4 timeout happened twice:

- https://travis-ci.org/IQSS/dataverse-client-python/jobs/63642048
- https://travis-ci.org/IQSS/dataverse-client-python/jobs/63643353

That was enough to make me disable it. We should open an issue. Please feel free to do so!

**Comment by rliebz** [comment]
@pdurbin, I've actually experienced some timeouts locally when trying to run tests in 3.4 since the python 3 compatibility merge, although I don't know the conditions that caused it.

I would say this is enough evidence to place the blame on an issue with this library (or one of its dependencies) and not travis. I would also recommend re-enabling travis even if builds are failing so that it is documented and we can easily test pull requests against it. 

If you'd rather not have failing tests, you can comment out the line in the yml file that includes python 3.4, but in that case make sure there is an open issue for 3.4 compatibility.

**Comment by rliebz** [comment]
Oh you already meant disabling 3.4. I thought you meant travis. You can ignore the last 2/3 of what I said.

**Pull request merged**
