### PR TITLE
[feature] optional timeout for get dataset methods, flake8, fast travis builds

### PR DESCRIPTION
**Pull request by icereval**

### CODE REVIEW

**Comment by rliebz** [comment]
Looks good to me. All ready for merge?

**Comment by garthg** [comment]
Per suggestion from @pdurbin , I'm posting to check if there's any connection between this and https://github.com/IQSS/dataverse/issues/2599 . 

I'm encountering a parse error from the get_dataset call in the python client when enumerating datasets in my dataverse. A test script with the traceback is pasted below. There is also additional discussion at https://github.com/IQSS/dataverse/issues/2441#issuecomment-143219955 .

```
$ cat rt227665_griffin.py 
from dataverse import Connection
from secrets import API_TOKEN
connection = Connection("dataverse.harvard.edu", API_TOKEN)
print "Got a dataverse connection."
dataverse = connection.get_dataverse("antislaverypetitionsma")
print "Got a Dataverse object: %s" % dataverse
for dataset in dataverse.get_datasets():
  # This will time out in get_datasets() because the dataverse is too big.
  print "Found a dataset..."
  print dataset.title, dataset.doi
  doi = dataset.doi  # Failing DOI is doi="doi:10.7910/DVN/WZMIPM".
  print "Try get_dataset_by_doi method..."
  dataset_by_doi = dataverse.get_dataset_by_doi(doi)
  print "Using get_dataset_by_doi method, found dataset:", dataset_by_doi.title

$ python rt227665_griffin.py 
Got a dataverse connection.
Got a Dataverse object: <dataverse.dataverse.Dataverse object at 0x7f7da180b5d0>
Traceback (most recent call last):
  File "rt227665_griffin.py", line 9, in <module>
    for dataset in dataverse.get_datasets():
  File "/opt/src/dataverse/dataverse/dataverse.py", line 138, in get_datasets
    entries = get_elements(collection_info, tag='entry')
  File "/opt/src/dataverse/dataverse/utils.py", line 21, in get_elements
    root = etree.XML(root)
  File "lxml.etree.pyx", line 3012, in lxml.etree.XML (src/lxml/lxml.etree.c:67861)
  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102455)
  File "parser.pxi", line 1673, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101284)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:96466)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 47
```

**Comment by pdurbin** [comment]
Yeah, I think the server is timing out when a dataverse has more than 4000 datasets so I was wondering if the "optional timeout for get dataset methods" commit at 01e2e86 would be a band-aid for @garthg until I get a chance to look at https://github.com/IQSS/dataverse/issues/2599 . (I'm quite busy with DDI export in https://github.com/IQSS/dataverse/issues/2579 right now.)

@rliebz I'm glad to see you here and nice to see some new commits by @icereval ! I'm always happy to see a growing list at https://github.com/IQSS/dataverse-client-python/graphs/contributors :)

**Comment by icereval** [comment]
@pdurbin, thanks!

Some background about the PR's origin here at COS:

Late last week we received a handful of 503 Service Unavailable responses. This was filtering down to our user's client browser as a 504 Gateway Timeout from their API call. Tracking this down we were able to identify it was the result of our UWSGI processes triggering the `harakiri` option and terminating the process after waiting 61 seconds for a response. Thus the PR to add an optional timeout, one could potentially avoid this rare case and allow the user to resubmit their api request at a later/better time.

Also, the travis build changes should bring you up to date and off the legacy travis build environment and  keep test run's down to about 1 minute (from 8).

**Comment by pdurbin** [comment]
@icereval great! Sounds completely unrelated to @garthg 's troubles though. Hmm. I've been meaning look into those "legacy" warnings from Travis so I might just steal whatever you've figured out. :) ... looks like it amounts to setting sudo to false: http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by icereval** [comment]
Yep, and the wheelhouse prevents the rebuild of lxml during each test.

**Comment by pdurbin** [comment]
Getting back to @garthg 's troubles for a moment, if @icereval and @rliebz could look at the new issue I just opened (#28), I'd appreciate it!

**Comment by rliebz** [comment]
Since @garthg's issue is unrelated and this PR looks good and backward compatible, I'm going to go ahead and merge it in.

**Comment by pdurbin** [comment]
As I mentioned at https://github.com/CenterForOpenScience/osf.io/pull/5344#issuecomment-222168095 I just noticed (half a year later!) that after this pull request was merged, the Travis build started failing: https://travis-ci.org/IQSS/dataverse-client-python/builds/84656583

@icereval @rliebz do know why? Thanks!

**Comment by rliebz** [comment]
I'm not sure that the issue is related to this pull request—GitHub indicated that the CI check passed at the time, and the failing build you linked is from a month ago.

Looking at the logs, it looks like the tests that are failing all seem to be triggered by the same issue, which has something to do with how files are being uploaded and received. A log like this I think is very indicative of the issue:
```
self = <dataverse.test.test_dataverse.TestDatasetOperations object at 0x7fb43ba72190>
    def test_upload_file(self):
        self.dataset.upload_file('file.txt', 'This is a simple text file!')
        self.dataset.upload_file('file2.txt', 'This is the second simple text file!')
        actual_files = [f.name for f in self.dataset.get_files()]
    
>       assert 'file.txt' in actual_files
E       assert 'file.txt' in ['temp-1.zip', 'temp.zip']
```

In the past, to upload files to the Dataverse through the SWORD API, we had to zip them and send them over, and the Dataverse host would unzip them for us automatically. What's happening here is that the file is being zipped locally, sent over, and then retrieved from the Dataverse host as a zip file.

@pdurbin—have there been any recent changes in the SWORD API or how file uploads are handled in the API, specifically? 

I would recommend opening up a new issue for this either way.

**Comment by pdurbin** [comment]
@rliebz my bad, since you said something I looked again at https://travis-ci.org/IQSS/dataverse-client-python/builds and now I see that there's a gap between the latest failed build (number 18, a month ago) and the one before that (number 10, a year ago):

screen shot 2016-06-01 at 8 11 40 am

**Comment by pdurbin** [comment]
I just re-ran the Travis build and it still failed. As @rliebz suggested, I have opened a new issue about this at #32.

**Pull request merged**
